### ISSUE TITLE
Allow elements in a row to have same height

### ISSUE THREAD

**Issue by btxtiger** [sam-1994/ngx-drag-and-drop-grid#1]
```css
::ng-deep .sam-drag-container {
      display: flex;
      flex-direction: column;
}
```

Just wanted to add, if you have cards or sth like this, and want to have them the same height in a row, this scss snippet allows to use `flex-grow: 1` on the child element (eg. <mat-card>) to fit the height.
